global using MediatR;
global using Application.Dtos.Common;
global using AutoMapper;
global using System.ComponentModel.DataAnnotations;
global using Domain.Entities;
global using Application.Exceptions;
global using Application.Interfaces.Repositories;
global using Application.Interfaces.Services;
global using Application.Interfaces;